### ISSUE TITLE
Downcase method.

### ISSUE THREAD

**Issue by shortstuffsushi** [BranchMetrics/Branch-Android-Invite-SDK#2]
Minor, but just noticed.

https://github.com/BranchMetrics/Branch-Android-Invite-SDK/blob/33a23640f247cda1da80a0390795636f3795c810/Branch-Invite-SDK/src/io/branch/invite/welcome/WelcomeHandler.java#L76

**Comment by sojanpr** [comment]
Thank you very much Graham. I will change it.

By the way I was not in office on the day you came. So missed to meet you.
How was your days in Bay area. Hope you had a nice trip.
Has winter started there?

Thanks
Sojan

**Comment by shortstuffsushi** [comment]
Yeah, sorry about that. I stopped by for all of maybe 10 minutes in the office on Tuesday... was planning to come back Thursday or Friday at some point, but got caught up being a tourist in SF :wink: The trip was pretty good this time out, got to see a lot more of the city since my girlfriend came with and actually *planned* things for us. Last time I just kind of wandered, which was still fun, but not real efficient or productive as far as seeing sites goes. Hope to make another trip out at some point, I'll definitely ping you guys again when I'm in the area. Oh, and no snow yet, just cooler (50-60) and leaves falling. My favorite time of the year.

**Comment by sojanpr** [comment]
Thanks @shortstuffsushi. The changes are added  on  the following PR 
https://github.com/BranchMetrics/Branch-Android-Invite-SDK/pull/5 . Do you think this will fix it?

**Comment by shortstuffsushi** [comment]
Yep.
