### ISSUE TITLE
Keys don't match iOS

### ISSUE THREAD

**Issue by shortstuffsushi** [BranchMetrics/Branch-Android-Invite-SDK#3]
I'm not sure how I missed this when you first wrote this, but the keys you made for the Android SDK don't match iOS. This is actually a huge problem :disappointed:
  * Invites won't work between platforms
  * Even if this is fixed, existing links won't work
  * To be backwards compatible, you'd really need to add both keys or something

**Comment by sojanpr** [comment]
Thanks @shortstuffsushi. The changes are added  on  the following PR 
https://github.com/BranchMetrics/Branch-Android-Invite-SDK/pull/5 . Do you think this will fix it?

**Comment by shortstuffsushi** [comment]
Well, it's not backwards compatible, but other than that, yes.

**Comment by sojanpr** [comment]
Since we are not looking forward to much compatibility issues now we are closing this issue. Changes will be available with next release.
