### ISSUE TITLE
Can't Customize Proceed to App button text

### ISSUE THREAD

**Issue by shortstuffsushi** [BranchMetrics/Branch-Android-Invite-SDK#4]
All the other fields on the page allow you to specify color, but the proceed button doesn't seem to be customizable. The default color does not work for all background colors, so it would be great to be able to customize that as well.

**Comment by shortstuffsushi** [comment]
The same is true of the buttons on the Invite Dialog, as far as I can tell. They're stuck on that blue value, unfortunately.

**Comment by sojanpr** [comment]
@shortstuffsushi  Thank you very much for the pointing these out.

For the first issue, Background cannot be customized for `proceed to app` button, the default welcome windows allows customization of `welcome` text and  `inviter info ` text only. SDK set the background of text view with text color of  other text view.  App can set any custom view by overriding `getCustomInvitationView()` call in the `WelcomeCallback` . Do you think that is enough for customizing the welcome screen?

For customising the invite screen there are builder methods

1)  `setTabStyle(Drawable,Drawable) `to set the tab style
2)  `setNegativeButtonStyle(int btnBackgroundResId, int btnTextResId, int textColorResId)` and
     `setPositiveButtonStyle(int btnBackgroundResId, int btnTextResId, int textColorResId)` to customise the action buttons. Do you this those are good enough?

**Comment by shortstuffsushi** [comment]
Why wouldn't you be able to change the button text color for the Proceed to App button? The default color doesn't work if you change the welcome/invite text colors, so it needs to be customizable as well.

For the invite, are Negative and Positive these buttons? These are the ones I'm referring to that need to be restyled.

![screen shot 2015-10-05 at 7 19 35 pm](https://cloud.githubusercontent.com/assets/1016147/10297246/0d9d1386-6b96-11e5-9f65-5db98ef7df62.png)

**Comment by sojanpr** [comment]
The default Welcome screen is devied in to 2 parts inviter info and Welcome info. Use can set only inviter info and Welcome text color. Welcome text color is used as the background for inviter info and vice versa.  Sorry there is no case  where the background color doesn't work but as you suggested it will provide more flexibility in selecting colors for the text. Will add  this.
    
Yes the  above show buttons are the positive and negative buttons

**Comment by shortstuffsushi** [comment]
Here's a simple case where not being able to change the background color doesn't work -- white background. Should be an easy enough add, though.

![screen shot 2015-10-05 at 8 50 42 pm](https://cloud.githubusercontent.com/assets/1016147/10298283/d0c8cb46-6ba2-11e5-800c-955cdb25e929.png)

The positive and negative does work, though my advice would be to change the default text color to #ededed, it's ever so slightly nicer to read.

![screen shot 2015-10-05 at 8 52 09 pm](https://cloud.githubusercontent.com/assets/1016147/10298299/f93b14bc-6ba2-11e5-835f-e98e81dd05cf.png)

I did this locally by changing the pos/neg styles as suggested, but that has a weird side effect. Since you want drawables for the background of the button, you end up getting the buttons appearing differently than the rest of the bar and not really fitting in (see screenshot, made intentionally ugly for clarity).

![screen shot 2015-10-05 at 8 54 04 pm](https://cloud.githubusercontent.com/assets/1016147/10298332/893599c0-6ba3-11e5-8a7c-968799ce5489.png)

I'm not sure of the API for this offhand, but you may want to allow them to just change the whole bar background. Also, providing a drawable feels weird, why not just a color?

**Comment by sojanpr** [comment]
@shortstuffsushi  Thank you very much for the detailed description and the images. It was really helpful.
 Added the following changes to the PR to address the issue.

1) We have added Customization support for `proceedToApp` button .New method added to `WelcomeViewStyle` set the style (`setProceedToAppButtonStyle(Drawable backgroundDrawable, int textColor`). Does it look like a good solution to the issue?

2) On `TabbedBuilder` did more color changes to make the test look better. Also added a method `setControlButtonBarBackground(Drawable drawable)` to the tabbed builder to set the background for the control bar (Bar which contains positive and negative buttons)

3)The  reason for giving backgrounds as `Drawable` than simply colors is to provide application to use different kind of drawables such as `AnimationDrawbles`, `Layer List`, `images`, `State Drawables` etc.
If you simply want to set color only you can use `new colorDraable(int colorCode)` . Does that make sense?

**Comment by shortstuffsushi** [comment]
Thanks @sojanpr, all the changes look like what I was hoping for. The drawable thing makes sense -- I didn't know the colorDrawable existed, blame my lack of Android knowledge. Thanks for all the updates.

**Comment by sojanpr** [comment]
@shortstuffsushi  Thank you very much. Changes will available with the next SDK release
